Repository trkhduy/BE-UberEats, pull requests merged in 2023-05, with the labels that each got.

#2 BE/api-restaurant-crud
  src/app.module.ts
  src/main.ts
  src/restaurant/dto/create-restaurant.dto.ts
  src/restaurant/dto/update-restaurant.dto.ts
  src/restaurant/entities/restaurant.entity.ts
  src/restaurant/restaurant.controller.spec.ts
  src/restaurant/restaurant.controller.ts
  src/restaurant/restaurant.module.ts
  src/restaurant/restaurant.service.spec.ts
  src/restaurant/restaurant.service.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: enhancement

#3 BE/update-api-register
  src/restaurant/dto/create-restaurant.dto.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/user.controller.ts
Labels: bug

#4 T3BE05 feat: api-voucher-crud
  src/app.module.ts
  src/restaurant/entities/restaurant.entity.ts
  src/restaurant/restaurant.module.ts
  src/voucher/dto/create-voucher.dto.ts
  src/voucher/dto/update-voucher.dto.ts
  src/voucher/entities/voucher.entity.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.module.ts
  src/voucher/voucher.service.ts
Labels: enhancement

#5 T3BE06 feat:BE/api-user_address-crud
  src/app.module.ts
  src/main.ts
  src/restaurant/restaurant.controller.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user_address/dto/create-user_address.dto.ts
  src/user_address/dto/update-user_address.dto.ts
  src/user_address/entities/user_address.entity.ts
  src/user_address/user_address.controller.ts
  src/user_address/user_address.module.ts
  src/user_address/user_address.service.ts
  src/voucher/voucher.controller.ts
Labels: enhancement

#6 T3BE01 feat:BE/api-login
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/constants.ts
  src/auth/dto/login.dto.ts
  src/auth/strategy/jwt.strategy.ts
  src/main.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: enhancement

#8 T3BE06 feat: api- category.
  src/app.module.ts
  src/category/category.controller.ts
  src/category/category.module.ts
  src/category/category.service.ts
  src/category/dto/create-category.dto.ts
  src/category/dto/update-category.dto.ts
  src/category/entities/category.entity.ts
  src/product/dto/update-product.dto.ts
  src/product/entities/product.entity.ts
  src/product/product.controller.ts
  src/product/product.module.ts
  src/product/product.service.ts
  src/voucher/dto/update-voucher.dto.ts
  src/voucher/voucher.service.ts
Labels: enhancement

#9 T3BE07 feat:BE/api-fillter-product
  package-lock.json
  package.json
  src/category/category.module.ts
  src/category/category.service.ts
  src/product/product.controller.ts
  src/product/product.service.ts
  src/restaurant/dto/update-restaurant.dto.ts
  src/restaurant/restaurant.controller.ts
  src/restaurant/restaurant.module.ts
  src/restaurant/restaurant.service.ts
  src/voucher/dto/create-voucher.dto.ts
  src/voucher/dto/update-voucher.dto.ts
  src/voucher/entities/voucher.entity.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.service.ts
  upload/asdsadsad.jfif
Labels: enhancement

#10 T3BE08 feat:BE/api-refreshToken
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/refreshToken.strategy.ts
  src/user/entities/user.entity.ts
Labels: enhancement

#11 Fix port login logout
  src/auth/auth.controller.ts
Labels: bug

#13 T3BE09 feat:BE/api-fillter-voucher
  package-lock.json
  package.json
  src/main.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.service.ts
Labels: enhancement

#14 Create Entity oder oder_detail status_oder
  src/app.module.ts
  src/oder/dto/create-oder.dto.ts
  src/oder/dto/update-oder.dto.ts
  src/oder/entities/order.entity.ts
  src/oder/entities/order_detail.entity.ts
  src/oder/order.controller.ts
  src/oder/order.module.ts
  src/oder/order.service.ts
  src/product/entities/product.entity.ts
  src/restaurant/entities/restaurant.entity.ts
  src/restaurant/restaurant.module.ts
  src/status_oder/dto/create-status_oder.dto.ts
  src/status_oder/dto/update-status_oder.dto.ts
  src/status_oder/entities/status_oder.entity.ts
  src/status_oder/status_oder.controller.ts
  src/status_oder/status_oder.module.ts
  src/status_oder/status_oder.service.ts
  src/user/entities/user.entity.ts
  src/user/user.module.ts
  src/user_address/entities/user_address.entity.ts
  src/user_address/user_address.module.ts
  src/voucher/entities/voucher.entity.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.service.ts
Labels: enhancement

#15 Be/api oder crud
  package-lock.json
  src/app.module.ts
  src/main.ts
  src/oder/dto/create-oder.dto.ts
  src/oder/dto/update-oder.dto.ts
  src/oder/entities/order.entity.ts
  src/oder/order.controller.ts
  src/oder/order.module.ts
  src/oder/order.service.ts
  src/product/dto/create-product.dto.ts
  src/restaurant/restaurant.module.ts
  src/user/entities/user.entity.ts
  src/user/user.module.ts
  src/user_address/user_address.module.ts
Labels: bug

#16 Fix bug return exception login
  src/auth/auth.service.ts
  upload/download.jpg
Labels: bug

#17 Be/api cart crud
  src/app.module.ts
  src/cart/cart.controller.ts
  src/cart/cart.module.ts
  src/cart/cart.service.ts
  src/cart/dto/create-cart.dto.ts
  src/cart/dto/update-cart.dto.ts
  src/cart/entities/cart.entity.ts
  src/oder/order.controller.ts
  src/product/dto/create-product.dto.ts
  src/product/entities/product.entity.ts
  src/product/product.controller.ts
  src/product/product.service.ts
  src/restaurant/dto/create-restaurant.dto.ts
  src/restaurant/restaurant.controller.ts
  src/restaurant/restaurant.service.ts
  src/user/entities/user.entity.ts
  src/voucher/voucher.controller.ts
Labels: bug

#18 update crud restaurant
  src/restaurant/dto/create-restaurant.dto.ts
  src/restaurant/dto/update-restaurant.dto.ts
  src/restaurant/entities/restaurant.entity.ts
  src/restaurant/restaurant.controller.ts
  src/restaurant/restaurant.service.ts
Labels: bug

#19 BE/api-card-crud
  src/cart/cart.controller.ts
  src/cart/cart.module.ts
  src/cart/cart.service.ts
  src/cart/dto/create-cart.dto.ts
  src/cart/dto/update-cart.dto.ts
  src/cart/entities/cart.entity.ts
  src/product/entities/product.entity.ts
  src/product/product.module.ts
  src/user/entities/user.entity.ts
  src/user/user.module.ts
Labels: enhancement

#20 create api orderdedtail
  src/app.module.ts
  src/oder/dto/create-oder.dto.ts
  src/oder/entities/order.entity.ts
  src/oder/entities/order_detail.entity.ts
  src/oder/order.module.ts
  src/oder/order.service.ts
  src/orderdetail/dto/create-orderdetail.dto.ts
  src/orderdetail/dto/update-orderdetail.dto.ts
  src/orderdetail/entities/orderdetail.entity.ts
  src/orderdetail/orderdetail.controller.ts
  src/orderdetail/orderdetail.module.ts
  src/orderdetail/orderdetail.service.ts
  src/product/dto/create-product.dto.ts
  src/product/dto/update-product.dto.ts
  src/product/entities/product.entity.ts
  src/product/product.controller.ts
  src/product/product.module.ts
  src/product/product.service.ts
  src/restaurant/dto/create-restaurant.dto.ts
  src/restaurant/dto/update-restaurant.dto.ts
  src/restaurant/entities/restaurant.entity.ts
  src/user/entities/user.entity.ts
  src/voucher/entities/voucher.entity.ts
Labels: enhancement

#21 BE/Api-update-user fix bug
  package-lock.json
  src/auth/strategy/jwt.strategy.ts
  src/main.ts
  src/product/dto/create-product.dto.ts
  src/product/dto/update-product.dto.ts
  src/product/entities/product.entity.ts
  src/product/product.controller.ts
  src/product/product.service.ts
  src/user/dto/update-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  upload/anh-03.jpg
Labels: bug, enhancement

#22 T3BE15 BE/Update return image
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/category/category.controller.ts
  src/category/category.module.ts
  src/category/category.service.ts
  src/category/dto/create-category.dto.ts
  src/category/dto/update-category.dto.ts
  src/category/entities/category.entity.ts
  src/product/product.controller.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.ts
  upload/test.png
Labels: bug, enhancement

#23 update api all
  src/orderdetail/dto/update-orderdetail.dto.ts
  src/orderdetail/orderdetail.controller.ts
  src/orderdetail/orderdetail.service.ts
  src/user_address/dto/create-user_address.dto.ts
  src/user_address/dto/update-user_address.dto.ts
  src/user_address/user_address.controller.ts
  src/user_address/user_address.service.ts
  src/voucher/dto/create-voucher.dto.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.service.ts
Labels: bug, good first issue

#24 update feat all
  src/restaurant/dto/create-restaurant.dto.ts
  src/restaurant/dto/update-restaurant.dto.ts
  src/restaurant/restaurant.controller.ts
  src/restaurant/restaurant.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  upload/sp1.jpg
Labels: bug

#25 Fix Bug
  src/restaurant/restaurant.controller.ts
  src/restaurant/restaurant.module.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  upload/uber.png
Labels: bug

#26 fix lan cuoi
  src/user/user.controller.ts
Labels: bug

#27 Update Api For CRUD-food-category-voucher ,LogOut
  src/auth/auth.controller.ts
  src/category/category.controller.ts
  src/category/category.service.ts
  src/category/dto/update-category.dto.ts
  src/product/product.controller.ts
  src/product/product.service.ts
  src/restaurant/entities/restaurant.entity.ts
  src/user/entities/user.entity.ts
  src/voucher/dto/create-voucher.dto.ts
  src/voucher/dto/update-voucher.dto.ts
  src/voucher/entities/voucher.entity.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.module.ts
  src/voucher/voucher.service.ts
Labels: bug

#28 BE/Update CRUD category
  src/category/category.service.ts
  src/category/dto/create-category.dto.ts
  src/category/dto/update-category.dto.ts
Labels: bug

#29 update get user
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: bug

#30 delete info password get user
  src/user/user.controller.ts
Labels: bug

#31 Update Feat: getNewProduct and getSaleProduct
  src/auth/strategy/jwt.strategy.ts
  src/main.ts
  src/product/product.controller.ts
  src/product/product.service.ts
  src/user/entities/user.entity.ts
  upload/default-avatar.png
Labels: enhancement

#32 Update CRUD api-cart
  src/cart/cart.controller.ts
  src/cart/cart.service.ts
  src/cart/dto/create-cart.dto.ts
  src/cart/dto/update-cart.dto.ts
  src/cart/entities/cart.entity.ts
  src/user/entities/user.entity.ts
  upload/crud_1.jpg
  upload/crud_2.jpg
  upload/crud_3.jpg
Labels: bug

#33 Add url img in cart
  src/cart/cart.controller.ts
Labels: bug

#34 update url image
  src/product/product.controller.ts
  upload/sp1.1.jpg
  upload/sp1.2.jpg
Labels: bug

#35 update Api get detail product and create api get product relate
  src/product/product.controller.ts
  src/product/product.service.ts
Labels: enhancement

#36 update Api userAddress
  src/user_address/dto/create-user_address.dto.ts
  src/user_address/dto/update-user_address.dto.ts
  src/user_address/entities/user_address.entity.ts
  src/user_address/user_address.controller.ts
  src/user_address/user_address.service.ts
Labels: bug, enhancement
