Repository trkhduy/BE-UberEats, pull requests merged in 2023-06, with the labels that each got.

#37 Update Api Cart
  src/cart/cart.controller.ts
  src/cart/cart.service.ts
  src/cart/entities/cart.entity.ts
  src/oder/dto/create-oder.dto.ts
  src/user_address/dto/create-user_address.dto.ts
  src/user_address/dto/update-user_address.dto.ts
  src/user_address/entities/user_address.entity.ts
  upload/bun-bo.jpg
  upload/com-ga.jpg
  upload/pho-ga.jpg
Labels: bug, enhancement

#39 Update Api order
  src/cart/entities/cart.entity.ts
  src/oder/dto/create-oder.dto.ts
  src/oder/dto/update-oder.dto.ts
  src/oder/entities/order.entity.ts
  src/oder/order.controller.ts
  src/oder/order.service.ts
  src/orderdetail/entities/orderdetail.entity.ts
  src/orderdetail/orderdetail.controller.ts
  src/orderdetail/orderdetail.service.ts
  src/restaurant/dto/create-restaurant.dto.ts
  src/restaurant/restaurant.controller.ts
  src/status_oder/entities/status_oder.entity.ts
  src/user/entities/user.entity.ts
  src/user_address/entities/user_address.entity.ts
  src/voucher/dto/create-voucher.dto.ts
  src/voucher/dto/update-voucher.dto.ts
  src/voucher/entities/voucher.entity.ts
Labels: bug

#40 Update api voucher
  src/user/user.controller.ts
  src/user/user.service.ts
  src/voucher/dto/create-voucher.dto.ts
  src/voucher/dto/update-voucher.dto.ts
  src/voucher/entities/voucher.entity.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.service.ts
Labels: bug, enhancement

#41 Be/test ws
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/category/dto/create-category.dto.ts
  src/oder/dto/create-oder.dto.ts
  src/oder/dto/update-oder.dto.ts
  src/oder/entities/order.entity.ts
  src/oder/order.controller.ts
  src/oder/order.module.ts
  src/oder/order.service.ts
  src/order-update/order-update.gateway.spec.ts
  src/order-update/order-update.gateway.ts
  src/order-update/order-update.module.ts
  src/orderdetail/orderdetail.service.ts
  src/product/dto/create-product.dto.ts
  src/restaurant/dto/create-restaurant.dto.ts
  src/status_oder/dto/create-status_oder.dto.ts
  src/status_oder/status_oder.module.ts
  src/user/entities/user.entity.ts
  src/user_address/dto/create-user_address.dto.ts
  src/voucher/voucher.controller.ts
  src/voucher/voucher.module.ts
  src/voucher/voucher.service.ts
  upload/banh-trang-nuong.jpg
  upload/com-cuon.jpg
  upload/com-tron.jpg
  upload/comga.jpg
  upload/ga-ran.jpg
  upload/nem-nuong.jpg
  upload/voucher.jpg
Labels: enhancement

#43 Update api get ordrer
  src/oder/order.service.ts
Labels: bug

#42 update socket v2
  src/oder/order.module.ts
  src/oder/order.service.ts
  src/order-update/order-update.gateway.ts
  src/order-update/order-update.module.ts
  src/order-update/order-update.service.ts
  src/orderdetail/dto/create-orderdetail.dto.ts
Labels: enhancement

#44 Update api get ordrer
  src/oder/order.service.ts
Labels: bug
